### ISSUE TITLE
Error 404 on README.md Links

### ISSUE THREAD

**Issue by saurabhhere** [NikhilM98/sugarizer-school-portal#2]
README Links given for Google Kubernetes Engine (GKE) and Microk8s (For bare-metal Kubernetes cluster) are showing Error 404: Page not Found

Lines in README.md:
`Google Kubernetes Engine (GKE) - README`
`Microk8s (For bare-metal Kubernetes cluster) - README`

**Comment by NikhilM98** [comment]
@saurabhhere Thanks for pointing it out. The description was not updated. I have fixed it in [07a4057](https://github.com/NikhilM98/sugarizer-school-portal/commit/07a4057222d46aa739a8e1e75a1ceff8dc1f2559).
